import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/frontend/providers/Providers";
import SideBar from "@/components/layout/SideBar/SideBar/SideBar";
import { Toaster } from "sonner";
import { SidebarInset } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EcoSphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f6f6f6]`}
      >
          <Providers>
            <Toaster position="top-right" />
            <SideBar />
          <SidebarInset>

            {/* <div className="w-full bg-background text-foreground"> */}
              {children}
            {/* </div> */}
          </SidebarInset>
            
          </Providers>
      </body>
    </html>
  );
}
