import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/frontend/providers/Providers";
import SideBar from "@/components/layout/SideBar/SideBar/SideBar";
import ReduxProvider from "@/Redux/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f6f6f6]`}
      >
        <ReduxProvider>
          <Providers>
            <SideBar />
            <div className="w-full bg-background text-foreground">
              {children}
            </div>
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
