import "reflect-metadata";
import { container } from "tsyringe";
import UserRepository from "../features/user/user.repository";
import UserService from "../features/user/user.service";
import AuthRepository from "../features/auth/auth.repository";
import RestaurantService from "../features/restaurant/restaurant.service";
import RestaurantRepository from "../features/restaurant/restaurant.repository";
import { RegistrationFactory } from "../features/auth/registration/registration.strategy.factory";
import { EndUserRegistration } from "../features/auth/registration/endUser.registration";
import { RegistrationService } from "../features/auth/registration/registration.service";
import { ShopRegistration } from "../features/auth/registration/shop.registration";
import { OrganizerRegistration } from "../features/auth/registration/organizer.registration";
import { LoginService } from "../features/auth/login/users.login.service";
import { ImageService } from "../services/image.service";
import { UploadService } from "../features/upload/upload.service";
import { UploadRepository } from "../features/upload/upload.repository";
import EventService from "../features/event/event.service";
import EventRepository from "../features/event/event.repository";
import { ProductRepository } from "../features/product/product.repository";
import { ProductService } from "../features/product/product.service";
import { RecycleService } from "../features/recycle/recycle.service";
import { RecycleRepository } from "../features/recycle/recycle.repository";
import { OrderRepository } from "../features/orders/order.repository";
import { OrderService } from "../features/orders/order.service";
import { PaymentService } from "../services/payment.service";
import { SubscriptionService } from "../features/subscription/subscription.service";
import { CouponRepository } from "../features/discountCoupon/coupon.repository";
import { CouponService } from "../features/discountCoupon/coupon.service";
import { AIRepository } from "../features/ai/ai.repository";
import { AIService } from "../features/ai/ai.service";

import { RecipeRepository } from "../features/recipe/recipe.repository";
import { RecipeService } from "../features/recipe/recipe.service";
import { SubscriptionRepository } from "../features/subscription/subscription.repository";
import { WebhookEventRepository } from "../features/webhookEvent/webhook.event.repository";

// you will register any
container.registerSingleton("IUserRepository", UserRepository);
container.registerSingleton("IUserService", UserService);
container.registerSingleton("IEventService", EventService);
container.registerSingleton("IEventRepository", EventRepository);
container.registerSingleton("IAuthRepository", AuthRepository);
container.registerSingleton("IRestaurantService", RestaurantService);
container.registerSingleton("IRestaurantRepository", RestaurantRepository);
container.registerSingleton("OrderRepository", OrderRepository);
container.registerSingleton("OrderService", OrderService);
container.registerSingleton("RegistrationService", RegistrationService);
container.registerSingleton("RegistrationFactory", RegistrationFactory);
container.registerSingleton("EndUserRegistration", EndUserRegistration);
container.registerSingleton("ShopRegistration", ShopRegistration);
container.registerSingleton("OrganizerRegistration", OrganizerRegistration);
container.registerSingleton("LoginService", LoginService);
container.registerSingleton("ImageService", ImageService);
container.registerSingleton("UploadService", UploadService);
container.registerSingleton("UploadRepository", UploadRepository);
container.registerSingleton("ProductRepository", ProductRepository);
container.registerSingleton("IProductRepository", ProductRepository); // Alias for OrderService
container.registerSingleton("ProductService", ProductService);
container.registerSingleton("PaymentService", PaymentService);
container.registerSingleton("SubscriptionService", SubscriptionService);
container.registerSingleton("SubscriptionRepository", SubscriptionRepository);
container.registerSingleton("WebhookRepository", WebhookEventRepository);
container.registerSingleton("RecycleService", RecycleService);
container.registerSingleton("RecycleRepository", RecycleRepository);
container.registerSingleton("CouponRepository", CouponRepository);
container.registerSingleton("CouponService", CouponService);
container.registerSingleton("AIRepository", AIRepository);
container.registerSingleton("AIService", AIService);
container.registerSingleton("RecipeRepository", RecipeRepository);
container.registerSingleton("RecipeService", RecipeService);

export { container as rootContainer } from "tsyringe";
