import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Providers } from "@/frontend/providers/Providers";
import SideBar from "@/components/layout/SideBar/SideBar/SideBar";
import { Toaster } from "sonner";
import { SidebarInset } from "@/components/ui/sidebar";
import SidebarTriggerBtn from "@/components/layout/SideBar/SidebarTriggerBtn/SidebarTriggerBtn";
import { AIChatWidget } from "@/components/layout/ai/AIChatWidget";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EcoSphere",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning={true}
    >
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f6f6f6]`}
      >
        <Providers locale={locale}>
          <Toaster position={locale === "ar" ? "top-left" : "top-right"} />
          <SideBar />
          <SidebarInset>
            <SidebarTriggerBtn />
            {children}
            <AIChatWidget />
          </SidebarInset>
        </Providers>
      </body>
    </html>
  );
}
