import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/frontend/providers/Providers";
import SideBar from "@/components/layout/SideBar/SideBar/SideBar";
import { Toaster } from "sonner";
import { SidebarInset } from "@/components/ui/sidebar";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EcoSphere",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f6f6f6]`}
      >
        <NextIntlClientProvider messages={messages} locale={locale} key={locale}>
          <Providers>
            <Toaster position="top-right" />
            <SideBar />
            <SidebarInset>

              {/* <div className="w-full bg-background text-foreground"> */}
              {children}
              {/* </div> */}
            </SidebarInset>

          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
