import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Providers } from "@/frontend/providers/Providers";
import SideBar from "@/components/layout/SideBar/SideBar/SideBar";
import { Toaster } from "sonner";
import { SidebarInset } from "@/components/ui/sidebar";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import SidebarTriggerBtn from "@/components/layout/SideBar/SidebarTriggerBtn/SidebarTriggerBtn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EcoSphere",
  description: "Generated by create next app",
};

import { AIChatWidget } from "@/components/features/ai/AIChatWidget";

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages({ locale });

  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f6f6f6]`}
      >
        <NextIntlClientProvider messages={messages} locale={locale} key={locale}>
          <Providers>
            <Toaster position="top-right" />
            <SideBar />
            <SidebarInset>
              <SidebarTriggerBtn/>
              {children}
              <AIChatWidget />
            </SidebarInset>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
